//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reverse.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reverse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250723_1556_Módulo_Triagem_Doméstica_simple_compose_01k0wa5mbtf17b1f5qfnn58zsd {
            get {
                object obj = ResourceManager.GetObject("20250723_1556_Módulo Triagem Doméstica_simple_compose_01k0wa5mbtf17b1f5qfnn58zsd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250723_1604_Módulo_Almoxarifado_simple_compose_01k0wap73vepdr2snpzy1f8tpj {
            get {
                object obj = ResourceManager.GetObject("20250723_1604_Módulo Almoxarifado_simple_compose_01k0wap73vepdr2snpzy1f8tpj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250723_1608_Módulo_RH_Criativo_simple_compose_01k0wavzwmeaq8rcjkpfjqr4mb {
            get {
                object obj = ResourceManager.GetObject("20250723_1608_Módulo RH Criativo_simple_compose_01k0wavzwmeaq8rcjkpfjqr4mb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250723_1611_Módulo_Financeiro_Ilustrado_simple_compose_01k0wb2b3be0qtt5t7q6ry2tby {
            get {
                object obj = ResourceManager.GetObject("20250723_1611_Módulo Financeiro Ilustrado_simple_compose_01k0wb2b3be0qtt5t7q6ry2t" +
                        "by", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250723_1629_Setor_Triagem_Ilustrado_remix_01k0wc2njmf7creq2p7yhvj108 {
            get {
                object obj = ResourceManager.GetObject("20250723_1629_Setor Triagem Ilustrado_remix_01k0wc2njmf7creq2p7yhvj108", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250723_1633_Setor_Almoxarifado_Ilustrado_remix_01k0wc9z41fa78c8mteezcz80d {
            get {
                object obj = ResourceManager.GetObject("20250723_1633_Setor Almoxarifado Ilustrado_remix_01k0wc9z41fa78c8mteezcz80d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250723_1637_Setor_Recursos_Humanos_remix_01k0wcgqs4ezvb7vrd27147a2n {
            get {
                object obj = ResourceManager.GetObject("20250723_1637_Setor Recursos Humanos_remix_01k0wcgqs4ezvb7vrd27147a2n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250723_1637_Setor_Recursos_Humanos_remix_01k0wcgqs4ezvb7vrd27147a2n1 {
            get {
                object obj = ResourceManager.GetObject("20250723_1637_Setor Recursos Humanos_remix_01k0wcgqs4ezvb7vrd27147a2n1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20250724_1051_Setor_Financeiro_Ilustrado_remix_01k0yb3tk5fwss77c2m3yc19kk {
            get {
                object obj = ResourceManager.GetObject("20250724_1051_Setor Financeiro Ilustrado_remix_01k0yb3tk5fwss77c2m3yc19kk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChatGPT_Image_23_de_jul__de_2025__15_47_43 {
            get {
                object obj = ResourceManager.GetObject("ChatGPT Image 23 de jul. de 2025, 15_47_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Login {
            get {
                object obj = ResourceManager.GetObject("Image Login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
